### ISSUE TITLE
Change language in weather city search

### ISSUE THREAD

**Issue by pololoko111** [oerlgrey/KravenHD#3]
https://github.com/oerlgrey/KravenHD/blob/ea7465333958ce49926a9199b982a03b9fad3001/usr/lib/enigma2/python/Plugins/Extensions/KravenHD/KravenHD.py#L2485

https://github.com/oerlgrey/KravenHD/blob/ea7465333958ce49926a9199b982a03b9fad3001/usr/lib/enigma2/python/Plugins/Extensions/KravenHD/KravenHD.py#L2510

After searching for a city or IP, it shows the results in German. 
Could you please change to English? or automatic detection of the language set in the weather settings?
Thank You.

**Comment by oerlgrey** [comment]
OK, i will check it.

**Comment by oerlgrey** [comment]
It's working.
Update is coming soon.

**Comment by oerlgrey** [comment]
https://github.com/oerlgrey/KravenHD/commit/382ce16553b20242b2eec14658904e6594fc9200#diff-d1e7e8d155a1d418b34de0f9f471f104096aaafe2ce7a13a444cf1c82a86f70f
