### ISSUE TITLE
OpenPLi support

### ISSUE THREAD

**Issue by julianxhokaxhiu** [oerlgrey/KravenHD#5]
Hi,

I'm not sure if I need to approach you for this as I'm kind of "new" to the Enigma2 scene. Is it possible to add your skin to the OpenPLi registry? I'm currently using OLi 7.3 and should be compatible.

Thank you in advance,
Julian

**Comment by oerlgrey** [comment]
Hi Julian,
this skin is only for openATV-Image, sorry.

**Comment by julianxhokaxhiu** [comment]
Allright, thanks :)
